baseURL = "https://themesfromart.com/"
defaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "en"
paginate = 5
theme = "hugo-theme-texify"
title = "Themes From Art"

disqusShortname = "themes-from-art"
googleAnalytics = "G-WPRZXLGMHX"
pygmentsUseClasses = true

[author]
name = "author"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true



[params]
  customCSS = []
  dateFormat = "2006-01-02"
  description = "an example site for hugo theme TeXify"
  enableFullRSS = true
  enableHanEmph = true
  enableMathjax = true
  favicon = "/favicon.ico"
  footnote = ""
  keywords = ["hugo", "latex", "theme"]