---
date: "2021-04-10"
description: the art used and themes
menu: main
title: 
---

Through Silence, posted on April 8, 2021, Themes from Art has discussed seven themes, eliciting subthemes from one poem, movie, rock song, and impressionist painting for each theme, a total of 28 artistic works.  The table below lists each of them by genre.

The second table groups the artistic works by theme.

```{r packages, echo=FALSE, warning=FALSE, message=FALSE}

library(tidyverse)

```


```{r artTable, echo=FALSE}
# create a data frame of strings sorted by theme and then genre
# made a copy of all the full URLs and the Bitly code at the bottom in case I need the latter, then removed them
urls <- data.frame(Theme = c("(https://themesfromart.com/post/2021-02-03-alcohol-woolf-nichols/)",
"(https://themesfromart.com/post/2021-02-03-alcohol-absinthe-degas/)", 
"(https://themesfromart.com/post/2021-01-24-alcohol-flood-frost/alcoholfloodindex/)",
"(https://themesfromart.com/post/2021-02-01-alcohol-margaritaville-buffet/)",
"(https://themesfromart.com/post/2021-02-08-decisions-sophie-s-choice-with-meryl-streep/decisionssophies/)", 
"(https://themesfromart.com/post/2021-02-08-decisions-the-card-players-a-painting-by-paul-cezanne/decisionscardplayerscezanne/)",
"(https://themesfromart.com/post/2021-02-08-decisions-from-the-road-not-taken-a-poem-by-robert-frost/decisionsroadfrost/)", 
"(https://themesfromart.com/post/2021-02-08-decisions-from-do-you-believe-in-magic-a-song-by-the-lovin-spoonful/decisionsmagicspoonful/)", 
"(https://themesfromart.com/post/2021-02-18-destruction-saving-private-ryan-a-movie-by-steven-spielberg/destructionsaving/)",
"(https://themesfromart.com/post/2021-02-18-destruction-from-flood-at-port-marly-a-painting-by-alfred-sisley/destructionflood/)",
"(https://themesfromart.com/post/2021-02-18-destruction-ozymandias-a-poem-by-percy-bysshe-shelley/destructoz/)", 
"(https://themesfromart.com/post/2021-02-18-destruction-from-my-hometown-a-rock-ballad-by-bruce-springsteen/destructhometown/)",
"(https://themesfromart.com/post/2021-02-26-workkane/workkane/)", "(https://themesfromart.com/post/2021-02-26-workscrapers/workscrapers/)",
"(https://themesfromart.com/post/2021-02-26-worksnowy/worksnowy/)",
"(https://themesfromart.com/post/2021-02-26-workproud/workproud/)",
"(https://themesfromart.com/post/2021-03-08-time-from-groundhog-day-starring-bill-murray/timegroundhog/)", 
"(https://themesfromart.com/post/2021-03-08-time-from-the-bellili-family-by-edgar-degas/timebellili/)",   
"(https://themesfromart.com/post/2021-03-08-time-to-his-coy-mistress-by-andrew-marvell/timecoy/)", 
"(https://themesfromart.com/post/2021-03-08-time-from-turn-turn-turn-by-the-byrds/timeturnturn/)", 
"(https://themesfromart.com/post/2021-03-14-chancedeerhunter/chancedeer/)",
"(https://themesfromart.com/post/2021-03-14-chancechurch/chancechurch/)",
"(https://themesfromart.com/post/2021-03-14-chancehap/chancehap/)",
"(https://themesfromart.com/post/2021-03-14-chancewinner/chancewinner/)",
"(https://themesfromart.com/post/silencenorthwest/)",
"(https://themesfromart.com/post/silenceavril/)",
"(https://themesfromart.com/post/2021-04-08-silencedonne/silencedonne/)",
"(https://themesfromart.com/post/2021-04-08-silencesounds/silencesounds/)",
"(https://themesfromart.com/post/2021-04-21-beauty-garden-at-sainte-adresse-from-a-painting-by-claude-monet/beautysainteadress/)",
"(https://themesfromart.com/post/2021-04-21-beauty-taxi-driver-a-movie-with-robert-de-niro-and-cybill-shepherd/beautytaxi/)",
"(https://themesfromart.com/post/2021-04-21-beauty-she-walks-in-beauty-a-poem-by-lord-byron/beautybyron/)", 
"(https://themesfromart.com/post/2021-04-21-beautyflack/beautyflack/)",
"(https://themesfromart.com/post/2021-05-03-death-from-bonnie-clyde-a-movie-starring-warren-beatty-and-faye-dunaway/deathbonnie/)",
"(https://themesfromart.com/post/2021-05-03-death-from-house-of-the-hanged-man-a-painting-by-paul-cezanne/deathhanged/)",
"(https://themesfromart.com/post/2021-05-03-death-from-death-be-not-proud-a-poem-by-john-donne/deathdonne/)",
"(https://themesfromart.com/post/2021-05-03-death-from-honey-sung-by-bobby-goldsboro/deathhoney/)"))

art <- readxl::read_xlsx(path = "C:/Users/Rees Morrison/Documents/R/Projects/CLIENTS/Themes/Art and Artists.xlsx")

#relocate columns, so that this sorts by Theme and then Genre
art <- art[  , c("Theme", "Genre", "Art", "Artist")]

# create URL for the Art
art$Art <- str_c("[", art$Art, "]", urls$Theme)

artTable <- kableExtra::kable(art)

artTable  # by genre and then chrono
artTablebyTheme <- art %>% arrange(Theme)

artTable.tab <- kableExtra::kable(artTablebyTheme)

artTable.tab # by theme

```

<!-- urls <- data.frame(Theme = c("(https://themesfromart.com/post/2021-02-03-alcohol-woolf-nichols/) -->
<!-- (https://themesfromart.com/post/2021-02-03-alcohol-absinthe-degas/ -->
<!-- (https://themesfromart.com/post/2021-01-24-alcohol-flood-frost/alcoholfloodindex/ -->
<!-- (https://themesfromart.com/post/2021-02-01-alcohol-margaritaville-buffet/ -->

<!-- (https://themesfromart.com/post/2021-02-03-alcohol-wide-view/ -->

<!-- ## Decisions -->
<!-- (https://themesfromart.com/post/2021-02-08-decisions-sophie-s-choice-with-meryl-streep/decisionssophies/  http://bit.ly/3v4iDqj -->
<!-- (https://themesfromart.com/post/2021-02-08-decisions-the-card-players-a-painting-by-paul-cezanne/decisionscardplayerscezanne/  http://bit.ly/38mqdCV -->
<!-- (https://themesfromart.com/post/2021-02-08-decisions-from-the-road-not-taken-a-poem-by-robert-frost/decisionsroadfrost/  http://bit.ly/3ekY031 -->
<!-- (https://themesfromart.com/post/2021-02-08-decisions-from-do-you-believe-in-magic-a-song-by-the-lovin-spoonful/decisionsmagicspoonful/  http://bit.ly/2OyvcJP -->
<!-- (https://themesfromart.com/post/2021-02-10-decisions-a-wider-angle-view/decisionswiderangle/ -->


<!-- ## Destruction put up Feb. 18, 2021 -->
<!-- (https://themesfromart.com/post/2021-02-18-destruction-saving-private-ryan-a-movie-by-steven-spielberg/destructionsaving/    http://bit.ly/38l5uzq -->
<!-- (https://themesfromart.com/post/2021-02-18-destruction-from-flood-at-port-marly-a-painting-by-alfred-sisley/destructionflood/  http://bit.ly/3t2LjhM -->
<!-- (https://themesfromart.com/post/2021-02-18-destruction-ozymandias-a-poem-by-percy-bysshe-shelley/destructoz/     http://bit.ly/30nAOcr -->
<!-- (https://themesfromart.com/post/2021-02-18-destruction-from-my-hometown-a-rock-ballad-by-bruce-springsteen/destructhometown/   http://bit.ly/3kUpga5 -->

<!-- (https://themesfromart.com/post/2021-02-18-destruction-a-wider-angle/destructionwide/ -->


<!-- ## Work put up Feb. 28, 2021 -->
<!-- (https://themesfromart.com/post/2021-02-26-workkane/workkane/   http://bit.ly/3rrEaXG -->
<!-- (https://themesfromart.com/post/2021-02-26-workscrapers/workscrapers/  http://bit.ly/30qjsLT -->
<!-- (https://themesfromart.com/post/2021-02-26-worksnowy/worksnowy/      http://bit.ly/30qi0tc -->
<!-- (https://themesfromart.com/post/2021-02-26-workproud/workproud/    http://bit.ly/3elYC8K -->

<!-- (https://themesfromart.com/post/2021-02-26-workadditional/workperspective/ -->

<!-- # Time put up March 9 but finished on March 11 with URLs   BITLYs are wrong -->
<!-- (https://themesfromart.com/post/2021-03-08-time-from-groundhog-day-starring-bill-murray/timegroundhog/ -->
<!--     http://bit.ly/2OGjCfq -->
<!-- (https://themesfromart.com/post/2021-03-08-time-from-the-bellili-family-by-edgar-degas/timebellili/   http://bit.ly/38qQZdn     -->
<!-- (https://themesfromart.com/post/2021-03-08-time-to-his-coy-mistress-by-andrew-marvell/timecoy/  http://bit.ly/3rDgShS -->
<!-- (https://themesfromart.com/post/2021-03-08-time-from-turn-turn-turn-by-the-byrds/timeturnturn/  http://bit.ly/3v3zhq9 -->

<!-- (https://themesfromart.com/post/2021-03-09-time-additional/timeadditional/   http://bit.ly/30p2yxi -->

<!-- ## Chance put up 3/20-22 -->
<!-- (https://themesfromart.com/post/2021-03-14-chancedeerhunter/chancedeer/ (https://bit.ly/2O9QXje -->
<!-- (https://themesfromart.com/post/2021-03-14-chancechurch/chancechurch/    (https://bit.ly/2PHUghU -->
<!-- (https://themesfromart.com/post/2021-03-14-chancehap/chancehap/  (https://bit.ly/39t2m5f -->
<!-- (https://themesfromart.com/post/2021-03-14-chancewinner/chancewinner/  (https://bit.ly/3cCGVAu -->

<!-- (https://themesfromart.com/post/2021-03-14-chanceadditional/chanceaddl/   (https://bit.ly/3sCJTKW -->

<!-- ## Silence -->
<!-- (https://themesfromart.com/post/silencenorthwest/  (https://bit.ly/31UeUyl -->
<!-- (https://themesfromart.com/post/silenceavril/    (https://bit.ly/2Q2vxVM -->
<!-- (https://themesfromart.com/post/2021-04-08-silencedonne/silencedonne/  (https://bit.ly/3fRk4mT -->
<!-- (https://themesfromart.com/post/2021-04-08-silencesounds/silencesounds/ (https://bit.ly/31V92oz -->

<!-- (https://themesfromart.com/post/2021-03-14-chanceadditional/chanceaddl/ (https://bit.ly/3dHVK4g -->

<!-- ## Beauty -->
<!-- (https://themesfromart.com/post/2021-04-21-beauty-garden-at-sainte-adresse-from-a-painting-by-claude-monet/beautysainteadress/  (https://bit.ly/3dDvI3g -->
<!-- (https://themesfromart.com/post/2021-04-21-beauty-taxi-driver-a-movie-with-robert-de-niro-and-cybill-shepherd/beautytaxi/       (https://bit.ly/3er5yzI -->
<!-- (https://themesfromart.com/post/2021-04-21-beauty-she-walks-in-beauty-a-poem-by-lord-byron/beautybyron/ (https://bit.ly/3sB967G -->
<!-- (https://themesfromart.com/post/2021-04-21-beautyflack/beautyflack/  (https://bit.ly/3sB967G -->
<!-- (https://themesfromart.com/post/2021-04-21-beauty-additional-subthemes/beautyaddl/  (https://bit.ly/2QpiEp9 -->

<!-- ## Death -->
<!-- (https://themesfromart.com/post/2021-05-03-death-from-bonnie-clyde-a-movie-starring-warren-beatty-and-faye-dunaway/deathbonnie/  (https://bit.ly/3vEXLW3 -->
<!-- (https://themesfromart.com/post/2021-05-03-death-from-house-of-the-hanged-man-a-painting-by-paul-cezanne/deathhanged/  (https://bit.ly/2QQD62s -->
<!-- (https://themesfromart.com/post/2021-05-03-death-from-death-be-not-proud-a-poem-by-john-donne/deathdonne/ (https://bit.ly/3xEen1Y -->
<!-- (https://themesfromart.com/post/2021-05-03-death-from-honey-sung-by-bobby-goldsboro/deathhoney/ (https://bit.ly/2Sf7Pqj -->

<!-- # collected additional posts, not in proper format for strings -->
<!-- # (https://themesfromart.com/post/2021-02-03-alcohol-wide-view/ -->
<!-- # (https://themesfromart.com/post/2021-02-10-decisions-a-wider-angle-view/decisionswiderangle/ -->
<!-- # (https://themesfromart.com/post/2021-02-18-destruction-a-wider-angle/destructionwide/ -->
<!-- # (https://themesfromart.com/post/2021-03-09-time-additional/timeadditional/   http://bit.ly/30p2yxi -->
<!-- # (https://themesfromart.com/post/2021-03-14-chanceadditional/chanceaddl/ (https://bit.ly/3dHVK4g -->
<!-- # (https://themesfromart.com/post/2021-04-21-beauty-additional-subthemes/beautyaddl/  (https://bit.ly/2QpiEp9 -->
<!-- # (https://themesfromart.com/post/2021-05-03-death-additional/deathaddl/ -->
<!-- (https://themesfromart.com/post/2021-05-03-death-additional/deathaddl/ -->
